---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-purger-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nginx-purger-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-purger-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-purger-clusterrole
subjects:
  - kind: ServiceAccount
    name: nginx-purger-serviceaccount
    namespace: default



